const Directions = {Up:38, Right: 39, Down: 40, Left: 37};

const SNAKE_SIZE = 5;
const WORM_SIZE = 5;
const GAME_SPEED = 1;
const LIVES_TOTAL = 5;
const SHIT_EATEN = 0;
const MANDAY_COUNTER = 0;
const MONEY_PER_DAY = 15000;
const START_KEY_STACK = [Directions.Up];
const BIT_X = 11;
const BIT_Y = 11;
const SPEED_START = 161;//IMPORTANTE
const SPEED_DIFF = 20;
const MESSAGE = 'SNAKE - ZDRAVIM OBA LUKASE,MIRU,LADU,JIRIHO,TOMASE,DAVIDA,ALCU,LEONKU,PETRA A OBA MILANY! POKUD JESTE HRAJES, VELIKA GRATULCE, MAS VELKYHO HADA - POWERED BY ICT COMEDIANTS - ';